FROM repo.paas.com:5000/paas/u14-ssh-jdk1.7 

MAINTAINER PaaS/allen

RUN locale-gen en_US.UTF-8 
#RUN echo "LC_ALL=en_US.UTF-8" > /etc/default/locale
RUN echo "LANG=en_US.UTF-8" >> /etc/default/locale
RUN echo "LANGUAGE=en_US:en" >> /etc/default/locale

#RUN echo "export LC_ALL=en_US.UTF-8" >> /root/.bashrc
RUN echo "export LANG=en_US.UTF-8" >> /root/.bashrc
RUN echo "export LANGUAGE=en_US:en" >> /root/.bashrc

EXPOSE 22

CMD /usr/sbin/sshd -D
